module.exports = {
  reforges: {
    perfect: 'diamond_atom',
    spiked: 'dragon_scale',
    fabled: 'dragon_claw',
    renowned: 'dragon_horn',
    cubic: 'molten_cube',
    reinforced: 'rare_diamond',
    magnetic: 'lapis_crystal',
    gilded: 'midas_jewel',
    fruitful: 'onyx',
    precise: 'optical_lens',
    ridiculous: 'red_nose',
    loving: 'red_scarf',
    suspicious: 'suspicious_vial',
    spiritual: 'spirit_stone',
    warped: 'warped_stone',
    shaded: 'dark_orb',
    giant: 'giant_tooth',
    empowered: 'sadans_brooch',
    moil: 'moil_log',
    dirty: 'dirt_bottle',
    toil: 'toil_log',
    refined: 'refined_amber',
    blessed: 'blessed_fruit',
    candied: 'candy_corn',
    sweet: 'rock_candy',
    submerged: 'deep_sea_orb',
    ancient: 'precursor_gear',
    withered: 'wither_blood',
    aote_stone: 'aote_stone',
    ambered: 'amber_material',
    jaded: 'jaderald',
    auspicious: 'rock_gemstone',
    fleet: 'diamonite'
  }
};
